on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
name: Bump homebrew
jobs:
  publish:
    name: Update homebrew-core
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Homebrew bump formula
        uses: dawidd6/action-homebrew-bump-formula@v3.8.0
        with:
          token: ${{ secrets.GH_HOMEBREW_TOKEN }}
          formula: dasel
          tap: homebrew/core
          force: true
